### PR TITLE
Deploy new alpha release

### PR DESCRIPTION
**Pull request by norbertkovacs95**

### CODE REVIEW

**Comment by rolandszoke** [comment]
Merged https://github.com/RisingStack/react-easy-state/pull/227

**Comment by rolandszoke** [comment]
Merged https://github.com/RisingStack/react-easy-state/pull/221

**Comment by rolandszoke** [comment]
Merged https://github.com/RisingStack/react-easy-state/pull/199

**Review by simonzsolt — APPROVED** [review]

**Review by rolandszoke — APPROVED** [review]

**Pull request merged**
